# Generated by Django 4.2.4 on 2023-09-25 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0005_sensor_measurements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='measurements',
        ),
    ]
